### ISSUE TITLE
Stable branch of Documenter site is stale

### ISSUE THREAD

**Issue by mikeingold** [mikeingold/MeshIntegrals.jl#103]
For some reason the Documenter site has not kept up with releases since about `v0.13.2`. The `dev` site is current, but the `stable` site has not been updated in some time. It looks like the `stable` site stopped being updated sometime around #70.

**Comment by JoshuaLampert** [comment]
After some more research I found the following:

* https://discourse.julialang.org/t/documenter-jl-does-not-build-on-tags-anymore-after-renaming-master-to-main/57171
From this I conclude that we should avoid using `[skip ci]` in commit messages. Looking at the commits for the releases of v0.13.4 and v0.14.0 we see that no actions were run, i.e. also not the documentation. This is because both corresponding PRs had commits including `[skip ci]`. After squash-merging all commits in these PRs also the final commit in main had `[skip ci]` in the commit message coming from the squashed commits, such that no actions were run.
* https://github.com/JuliaDocs/Documenter.jl/issues/2137 and https://discourse.julialang.org/t/building-docs-with-documenter-jl/63159
Can you please double-check that the `DOCUMENTER_KEY` secret in the repo is set up correctly? This could be the issue because TagBot [uses it](https://github.com/mikeingold/MeshIntegrals.jl/blob/main/.github/workflows/TagBot.yml#L15) and TagBot was introduced in between v0.13.2 and v0.13.3.
* See also https://discourse.julialang.org/t/latest-version-of-docs-not-published-github-actions-tagbot/50634/19 and https://m3g.github.io/JuliaNotes.jl/stable/publish_docs/ and https://github.com/SKopecz/PositiveIntegrators.jl/issues/55
Especially interesting for how to redeploy the missing documentation for the last few releases.

To conclude, my hope is that the `DOCUMENTER_KEY` is not set up (correctly).
If that is the case we should set it up correctly and create a new release to test if it works. Once it works we can try to manually create new tags for the old versions that are missing the docs as explained in one of the links of the third point above.
If, on the other hand, `DOCUMENTER_KEY` is set up correctly, we could still try to manually create a new tag for, say, v0.13.3 to see whether at least this works in order to get the docs for the tags.

**Comment by mikeingold** [comment]
> * Can you please double-check that the `DOCUMENTER_KEY` secret in the repo is set up correctly? This could be the issue because TagBot [uses it](https://github.com/mikeingold/MeshIntegrals.jl/blob/main/.github/workflows/TagBot.yml#L15) and TagBot was introduced in between v0.13.2 and v0.13.3.

I think this was the problem 🤦‍♂️ 

I just set up the key and secret and they should be good to go now.

**Comment by mikeingold** [comment]
I pushed a new release v0.15.1 (only incorporates #105) and it looks like docs are now deploying as expected. Looks like we'll just need to push a couple of tags to capture some missed versions.

**Comment by JoshuaLampert** [comment]
Nice!

**Comment by mikeingold** [comment]
I just pushed a few `-bump` tags to re-trigger TagBot. If the docs page looks correct once the Actions complete, then I'll go ahead and close this Issue.

**Comment by mikeingold** [comment]
I'm not sure if bumping past tags fixed those prior docs. TagBot really doesn't want to run for the `v0.14.0` commit for some reason. The `v0.13.5-bump` and `v0.14.1` commits triggered and show up in the `gh-pages` root dir, but they don't seem to be visible on the site.

**Comment by JoshuaLampert** [comment]
Yeah, it didn't really do what we hoped for. The list of versions https://github.com/mikeingold/MeshIntegrals.jl/blob/gh-pages/versions.js in the github_pages branch is not updated.

**Comment by mikeingold** [comment]
Well, if we're confident that the issue is fixed moving forward then I'm not sure how much value there is to continuing to debug this for past versions (especially given how sparse the docs have been to this point anyway).

**Comment by JoshuaLampert** [comment]
I agree. Let's just close the issue.
